const mockMissions = [
  {
    id: 1,
    title: "Complete React Hooks Exercise",
    description:
      "Build a custom hook for managing form state with validation. Submit your solution with proper documentation and test cases.",
    teacher: "Dr. Sarah Wilson",
    course: "Advanced React Development",
    courseColor: "bg-blue-500",
    points: 50,
    deadline: new Date(Date.now() + 86400000 * 2),
    status: "pending",
    difficulty: "intermediate",
    estimatedTime: "45 mins",
    type: "coding",
    submissions: 0,
    maxSubmissions: 3,
  },
  {
    id: 2,
    title: "Database Design Quiz",
    description:
      "Complete the multiple-choice quiz covering normalization, indexing, and query optimization concepts.",
    teacher: "Prof. Michael Chen",
    course: "Database Systems",
    courseColor: "bg-green-500",
    points: 30,
    deadline: new Date(Date.now() + 86400000),
    status: "completed",
    difficulty: "beginner",
    estimatedTime: "20 mins",
    type: "quiz",
    completedAt: new Date(Date.now() - 3600000),
    score: 85,
  },
  {
    id: 3,
    title: "UI/UX Design Critique",
    description:
      "Analyze the provided mobile app interface and submit a detailed critique covering usability, accessibility, and visual design principles.",
    teacher: "Emma Rodriguez",
    course: "User Experience Design",
    courseColor: "bg-purple-500",
    points: 40,
    deadline: new Date(Date.now() + 86400000 * 3),
    status: "in_progress",
    difficulty: "advanced",
    estimatedTime: "60 mins",
    type: "assignment",
    submissions: 1,
    maxSubmissions: 2,
  },
  {
    id: 4,
    title: "Python Algorithm Challenge",
    description:
      "Solve the binary tree traversal problem using both recursive and iterative approaches. Include time complexity analysis.",
    teacher: "Dr. James Park",
    course: "Data Structures & Algorithms",
    courseColor: "bg-orange-500",
    points: 60,
    deadline: new Date(Date.now() - 86400000),
    status: "overdue",
    difficulty: "advanced",
    estimatedTime: "90 mins",
    type: "coding",
    submissions: 0,
    maxSubmissions: 1,
  },
  {
    id: 5,
    title: "Weekly Reading Reflection",
    description:
      "Write a 500-word reflection on this week's assigned reading about machine learning ethics and bias in AI systems.",
    teacher: "Dr. Lisa Thompson",
    course: "AI Ethics & Society",
    courseColor: "bg-teal-500",
    points: 25,
    deadline: new Date(Date.now() + 86400000 * 4),
    status: "pending",
    difficulty: "beginner",
    estimatedTime: "30 mins",
    type: "essay",
    submissions: 0,
    maxSubmissions: 1,
  },
];

const mockAchievements = [
  {
    id: 1,
    title: "Week Warrior",
    description: "Completed all tasks for 7 consecutive days",
    icon: "Trophy",
    color: "text-yellow-500",
    earnedAt: new Date(Date.now() - 86400000),
  },
  {
    id: 2,
    title: "Quick Learner",
    description: "Completed 10 tasks in under estimated time",
    icon: "Zap",
    color: "text-blue-500",
    earnedAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    id: 3,
    title: "Perfect Score",
    description: "Achieved 100% on 5 different quizzes",
    icon: "Star",
    color: "text-purple-500",
    earnedAt: new Date(Date.now() - 86400000 * 5),
  },
];

const mockStudentData = {
  name: "Alex Johnson",
  avatar:
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  walletAddress: "0x742d35Cc6634C0532925a3b8D4C0532925a3b8D4",
  balance: 2.4567,
  totalPoints: 1250,
  dailyGoal: 5,
  completedToday: 3,
  streak: 7,
  level: 12,
  nextLevelPoints: 1500,
  enrolledCourses: 4,
  totalTasksCompleted: 89,
};

export { mockAchievements, mockMissions, mockStudentData };
